### ISSUE TITLE
baidu  access problem for downloading dataset(coz foreigner)

### ISSUE THREAD

**Issue by hws203** [ShanghaiTech-IMPACT/Geometry-Aware-Attenuation-Learning-for-Sparse-View-CBCT-Reconstruction#1]
@Zhentao-Liu Could you make a google link(or XNAT) for the prepared data set downloading?  I can not make a baidu account for foreigner problem.

**Comment by Zhentao-Liu** [comment]
I’ve uploaded my dataset (spine, dental) in google drive in following link: https://drive.google.com/drive/folders/1lohU5e9oiGehK3F6W8etLlMYCWI04qnW?usp=drive_link. You can check it and I think it's enough for your verification. 

As for walnut dataset, I do not have enough free space in google drive. You may refer to the link to [walnut scan](https://github.com/cicwi/WalnutReconstructionCodes), and process it according to the description in my paper.

**Comment by hws203** [comment]
Thanks very much. Now I can download it.
