### ISSUE TITLE
pretrained ckpt file downloading request

### ISSUE THREAD

**Issue by hws203** [ShanghaiTech-IMPACT/Geometry-Aware-Attenuation-Learning-for-Sparse-View-CBCT-Reconstruction#4]
@Zhentao-Liu Could I download your pretrained ckpt file of 200 epoch ?   Below is my dental train running capture. As you can see it, one epoch consume about 10 hours with my rtx-3090ti 24GB GPU. So I needs about 200x10=2000 hours to get the epoch 200 ckpt file.

I hope to download your more 200 epoch run ckpt file of dental or spine sample, both will be better for me. 

<img width="1122" alt="train_01" src="https://github.com/user-attachments/assets/7f5419cf-7c63-4c36-be58-8adf005eb92d">
<img width="1116" alt="train_02" src="https://github.com/user-attachments/assets/453633d9-352b-4114-b3a8-543207e54b8f">

**Comment by Zhentao-Liu** [comment]
I will upload my weights later today. TBC.



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 22, 2024 04:42 AM
To: ***@***.***&gt;;
Cc: "Zhentao ***@***.******@***.***&gt;;
Subject: [ShanghaiTech-IMPACT/Geometry-Aware-Attenuation-Learning-for-Sparse-View-CBCT-Reconstruction]pretrained ckpt file downloading request (Issue #4)




 
@Zhentao-Liu Could I download your pretrained ckpt file of 200 epoch ?   Below is my dental train running capture. As you can see it, one epoch consume about 10 hours with my rtx-3090ti 24GB GPU. So I needs about 200x10=2000 hours to get the epoch 200 ckpt file.
 
I hope to download your more 200 epoch run ckpt file of dental or spline sample, both will be better for me.
 train_01.PNG (view on web) train_02.PNG (view on web)

**Comment by hws203** [comment]
@Zhentao-Liu Can I test your weight file, Today?

**Comment by Zhentao-Liu** [comment]
Hi there. I am sorry that the original weights have been removed for server data cleaning. I quickly trained a net on dental dataset in the following conditions: views=10, scale=4, uniform angle samplin in range of [0, 360), epoch=100. The weight has been uploaded onto the [dataset link](https://drive.google.com/drive/folders/1lohU5e9oiGehK3F6W8etLlMYCWI04qnW?usp=drive_link). This may be slightly different from the results in the paper. You may download it for a quick verification. Hope this can help you.

**Comment by hws203** [comment]
Yes, I can see that there are a little different, volume's ssim avg=0.848. Your model inference time is fast under 0.02s at log with my gpu too which is good for me, but gpu memory usage is a liitle big(14GB).  

<img width="1087" alt="eval" src="https://github.com/user-attachments/assets/da9da663-e8e6-428e-8abe-7bfbd4967370">

**Comment by Zhentao-Liu** [comment]
Glad to see it works for you. Yes, my model is GPU memory consuming which is one of its limitations. Further improvements need to be done.
