### ISSUE TITLE
train

### ISSUE THREAD

**Issue by he0713** [ShanghaiTech-IMPACT/Geometry-Aware-Attenuation-Learning-for-Sparse-View-CBCT-Reconstruction#5]
Hello, I followed your instructions to do the DRR simulation and got the projection map, but there is the following error during training, I don't know where the problem is, please let me know.
![屏幕截图 2024-12-24 200331](https://github.com/user-attachments/assets/d31442c4-a316-48ac-8930-dbdca516ada1)

**Comment by Zhentao-Liu** [comment]
It seems that it is a question about the dataset path argument. How about set the `-D` argument as full path of your dataset rather than relative path. Maybe it would work. Just try to debug it.

**Comment by he0713** [comment]
Thank you
